# Generated by Django 2.0 on 2018-07-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180711_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_end_flag',
            field=models.IntegerField(default=0),
        ),
    ]
